name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        R -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")'
        R -e 'devtools::install_github("rstudio/bookdown")'
        R -e 'install.packages(c("bookdown", "kableExtra", "shiny", "learnr"))'

    - name: Render book
      run: Rscript -e 'bookdown::render_book("index.Rmd")'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book