name: Deploy Bookdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    - name: Install Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/3.1.6/pandoc-3.1.6-1-amd64.deb
        sudo dpkg -i pandoc-3.1.6-1-amd64.deb
        pandoc --version

    - name: Install TinyTeX
      run: |
        Rscript -e "install.packages('tinytex', repos = 'https://cloud.r-project.org')"
        Rscript -e "tinytex::install_tinytex()"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev libpng-dev libjpeg-dev libtiff-dev zlib1g-dev

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("bookdown", "kableExtra", "knitr", "rmarkdown", "systemfonts", "svglite"), repos = "https://cloud.r-project.org")'

    - name: Generate PDF
      run: |
        Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
        mv tesis.pdf docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages