name: Deploy Bookdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    - name: Install TinyTeX
      run: |
        Rscript -e "install.packages('tinytex', repos = 'https://cloud.r-project.org')"
        Rscript -e "tinytex::install_tinytex()"

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("bookdown", "kableExtra", "knitr", "rmarkdown"), repos = "https://cloud.r-project.org")'

    - name: Generate PDF
      run: |
        Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
        mv tesis.pdf docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages