name: Deploy Bookdown

on:
  push:
    branches:
      - main  # Cambia esto a la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        sudo apt-get install libfontconfig1-dev
    
    - name: Install libxml2
      run: |
        sudo apt-get install -y libxml2 libxml2-dev
    
    - name: Install TinyTeX
      run: |
        Rscript -e 'install.packages("tinytex")'
        Rscript -e 'tinytex::install_tinytex()'
        Rscript -e 'tinytex::tlmgr_install("multirow")'  # Instalar el paquete multirow

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("bookdown", "kableExtra", "shiny", "learnr", "xml2"))'

    - name: Render book to GitBook
      run: |
        Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook", output_dir = "docs")'

